Itineraire:
    type: entity
    table: itineraire
    indexes:
        fk_itineraire_auteur_idx:
            columns:
                - auteur
        fk_itineraire_diff_idx:
            columns:
                - difficulte
        fk_itineraire_trace_idx:
            columns:
                - trace
        fk_itineraire_status_idx:
            columns:
                - status
        fk_itineraire_typechemin_idx:
            columns:
                - typechemin
        fk_itineraire_segment_idx:
            columns:
                - segment
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        datecreation:
            type: date
            nullable: false
            comment: ''
        longueur:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        deniveleplus:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        denivelemoins:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        description:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        numero:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        public:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        segment:
            type: linestring
            nullable: false
            comment: ''
            requireSQLConversion: true
        elevation:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    manyToOne:
        auteur:
            targetEntity: Utilisateur
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                auteur:
                    referencedColumnName: id
            orphanRemoval: false
        difficulte:
            targetEntity: Difficulteparcours
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                difficulte:
                    referencedColumnName: id
            orphanRemoval: false
        status:
            targetEntity: Status
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                status:
                    referencedColumnName: id
            orphanRemoval: false
        trace:
            targetEntity: Trace
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                trace:
                    referencedColumnName: id
            orphanRemoval: false
        typechemin:
            targetEntity: Typechemin
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                typechemin:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        utilisateurid:
            targetEntity: Utilisateur
            cascade: {  }
            mappedBy: itineraireid
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
