Role:
    type: entity
    table: role
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        label:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
    manyToMany:
        permission:
            targetEntity: Permission
            cascade: {  }
            mappedBy: null
            inversedBy: role
            joinTable:
                name: role_has_permission
                joinColumns:
                    -
                        name: role_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: permission_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
