Segment:
    type: entity
    table: segment
    indexes:
        fk_segment_trace1_idx:
            columns:
                - pog1
        fk_segment_coordonnees1_idx:
            columns:
                - pog2
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        sens:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        trace:
            type: linestring
            nullable: false
            comment: ''
            requireSQLConversion: true
        elevation:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
    manyToOne:
        pog1:
            targetEntity: Point
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                pog1:
                    referencedColumnName: id
            orphanRemoval: false
        pog2:
            targetEntity: Point
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                pog2:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        idpop:
            targetEntity: Point
            cascade: {  }
            mappedBy: idsegment
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
