Typelieu:
    type: entity
    table: typelieu
    indexes:
        fk_typelieu_icone1_idx:
            columns:
                - icone
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        label:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        icone:
            targetEntity: Icone
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                icone:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
