Utilisateur:
    type: entity
    table: utilisateur
    indexes:
        fk_utilisateur_role_idx:
            columns:
                - role
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        nom:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        datenaissance:
            type: date
            nullable: true
            comment: ''
        telephone:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        role:
            targetEntity: Role
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                role:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        itineraireid:
            targetEntity: Itineraire
            cascade: {  }
            mappedBy: null
            inversedBy: utilisateurid
            joinTable:
                name: utilisateurhasitineraire
                joinColumns:
                    -
                        name: utilisateurId
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: itineraireId
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
