site_carto_homepage:
    path:     /
    defaults: { _controller: SiteCartoBundle:Map:index }
site_carto_itineraire:
    path:     /itineraire
    defaults: { _controller: SiteCartoBundle:Itineraire:index }
