site_carto_homepage:
    path:     /
    defaults: { _controller: SiteCartoBundle:Default:index }
site_carto_mapPage:
    path:     /carte
    defaults: { _controller: SiteCartoBundle:Map:index }
site_carto_itineraire:
    path:     /itineraire
    defaults: { _controller: SiteCartoBundle:Itineraire:index }
site_carto_getDifficulteParcours:
    path:    /itineraire_getDifficultes
    defaults: { _controller:SiteCartoBundle:Itineraire:getDifficultes }
    options:
        expose: true
site_carto_getStatus:
    path:    /itineraire_getStatus
    defaults: { _controller:SiteCartoBundle:Itineraire:getStatus }
    options:
        expose: true
site_carto_getTypechemin:
    path:    /itineraire_getTypechemin
    defaults: { _controller:SiteCartoBundle:Itineraire:getTypechemin }
    options:
        expose: true
site_carto_saveItineraire:
    path:    /itineraire_save
    defaults: { _controller:SiteCartoBundle:Itineraire:save }
    options:
        expose: true
site_carto_loadItineraire:
    path:    /itineraire_load/{id}
    defaults: { _controller:SiteCartoBundle:Itineraire:load }
    options:
        expose: true
site_carto_getPoi:
    path:    /poi_get
    defaults: { _controller:SiteCartoBundle:Poi:getPoi }
    options:
        expose: true
site_carto_savePoi:
    path:    /poi_save
    defaults: { _controller:SiteCartoBundle:Poi:savePoi}
    options:
        expose: true
site_carto_getAllLieux:
    path:    /poi_getAllLieux
    defaults: { _controller:SiteCartoBundle:Typelieu:getAllLieux }
    options:
        expose: true
site_carto_getAllPois:
    path:    /poi_getAllPois
    defaults: { _controller:SiteCartoBundle:Poi:getAllPois }
    options:
        expose: true
site_carto_getAllIcones:
    path:    /poi_getAllIcones
    defaults: { _controller:SiteCartoBundle:Icones:getAllIcones }
    options:
        expose: true
site_carto_upload:
    path:     /upload
    defaults: { _controller: SiteCartoBundle:Map:upload }
site_carto_submitupload:
    path:     /sub_upload
    defaults: { _controller: SiteCartoBundle:Map:submit }
site_carto_uploadIcone:
    path:     /uploadIcone
    defaults: { _controller: SiteCartoBundle:Typelieu:uploadIcone }
site_carto_submituploadIcone:
    path:     /submituploadIcone/
    defaults: { _controller: SiteCartoBundle:Typelieu:submituploadIcone }
    options:
        expose: true
site_carto_recherche_itineraire:
    path:     /recherche
    defaults: { _controller: SiteCartoBundle:Itineraire:recherche }
site_carto_fiche:
    path:     /fiche
    defaults: { _controller: SiteCartoBundle:User:profil }
site_carto_submitFiche:
    path:     /submit_fiche
    defaults: { _controller: SiteCartoBundle:User:profilSubmit }
site_carto_createUser:
    path:    /user/create
    defaults: { _controller:SiteCartoBundle:User:create }
site_carto_loadRoles:
    path:    /user/loadRoles
    defaults: { _controller:SiteCartoBundle:User:loadRoles }
site_carto_getAllUsers:
    path:    /user/all
    defaults: { _controller:SiteCartoBundle:User:getAllUsers }
site_carto_annuaire:
    path:    /user/annuaire
    defaults: { _controller:SiteCartoBundle:User:annuaire }
site_carto_deleteUser:
    path:    /user/delete
    defaults: { _controller:SiteCartoBundle:User:delete }
site_carto_getUser:
    path:    /user/get
    defaults: { _controller:SiteCartoBundle:User:getUser }
site_carto_updateUser:
    path:    /user/update
    defaults: { _controller:SiteCartoBundle:User:updateUser }
site_carto_getUserActivation:
    path:    /user/getActivation
    defaults:  { _controller:SiteCartoBundle:User:getUserActivation }
site_carto_changePassword:
    path:    /user/changePassword
    defaults:  { _controller:SiteCartoBundle:User:changePassword }
login_check:
    path:   /login_check
    defaults: { _controller:SiteCartoBundle:User:logIn }
logout:
    path:   /logout
    defaults: { _controller:SiteCartoBundle:User:logOut }
site_carto_recherche_itineraire:
    path:     /list
    defaults: { _controller: SiteCartoBundle:Itineraire:itilist }
site_carto_segment_update:
    path:     /segment_update
    defaults: { _controller: SiteCartoBundle:Segment:update }
    options:
        expose: true
site_carto_saveSegment:
    path:    /segment_save
    defaults: { _controller:SiteCartoBundle:Itineraire:saveSegment }
    options:
        expose: true
site_carto_loadSegment:
    path:    /segmentload
    defaults: { _controller:SiteCartoBundle:Itineraire:loadSegment }
