site_carto_homepage:
    path:     /
    defaults: { _controller: SiteCartoBundle:Default:index }
site_carto_mapPage:
    path:     /carte
    defaults: { _controller: SiteCartoBundle:Map:index }
site_carto_itineraire:
    path:     /itineraire
    defaults: { _controller: SiteCartoBundle:Itineraire:index }
site_carto_getDifficulteParcours:
    path:    /itineraire_getDifficultes
    defaults: { _controller:SiteCartoBundle:Itineraire:getDifficultes }
    options:
        expose: true
site_carto_getStatus:
    path:    /itineraire_getStatus
    defaults: { _controller:SiteCartoBundle:Itineraire:getStatus }
    options:
        expose: true
site_carto_getTypechemin:
    path:    /itineraire_getTypechemin
    defaults: { _controller:SiteCartoBundle:Itineraire:getTypechemin }
    options:
        expose: true
site_carto_saveItineraire:
    path:    /itineraire_save
    defaults: { _controller:SiteCartoBundle:Itineraire:save }
    options:
        expose: true
site_carto_loadItineraire:
    path:    /itineraire_load/{id}
    defaults: { _controller:SiteCartoBundle:Itineraire:load }
    options:
        expose: true
site_carto_getPoi:
    path:    /poi_get
    defaults: { _controller:SiteCartoBundle:Poi:getPoi }
    options:
        expose: true
site_carto_savePoi:
    path:    /poi_save
    defaults: { _controller:SiteCartoBundle:Poi:savePoi}
    options:
        expose: true
site_carto_getAllLieux:
    path:    /poi_getAllLieux
    defaults: { _controller:SiteCartoBundle:Typelieu:getAllLieux }
    options:
        expose: true
site_carto_getAllPois:
    path:    /poi_getAllPois
    defaults: { _controller:SiteCartoBundle:Poi:getAllPois }
    options:
        expose: true
site_carto_getAllIcones:
    path:    /poi_getAllIcones
    defaults: { _controller:SiteCartoBundle:Icones:getAllIcones }
    options:
        expose: true
site_carto_upload:
    path:     /upload
    defaults: { _controller: SiteCartoBundle:Map:upload }
site_carto_submitupload:
    path:     /sub_upload
    defaults: { _controller: SiteCartoBundle:Map:submit }
<<<<<<< HEAD
site_carto_uploadIcone:
    path:     /uploadIcone
    defaults: { _controller: SiteCartoBundle:Typelieu:uploadIcone }
site_carto_submituploadIcone:
    path:     /submituploadIcone/
    defaults: { _controller: SiteCartoBundle:Typelieu:submituploadIcone }
    options:
        expose: true
site_carto_recherche_itineraire:
    path:     /recherche
    defaults: { _controller: SiteCartoBundle:Itineraire:recherche }
site_carto_fiche:
    path:     /fiche
    defaults: { _controller: SiteCartoBundle:User:index }
